## Dependencies ----
## Add one line by package you want to add as dependency
usethis::use_package( "dplyr" )
usethis::use_package( "tidyr" )
usethis::use_package( "purrr" )
usethis::use_package( "stringr" )
usethis::use_package( "ggplot2" )
usethis::use_package( "tibble" )
usethis::use_package( "scales" )
usethis::use_package( "readxl" )
usethis::use_package( "writexl" )
usethis::use_package( "waiter" )
usethis::use_package( "shinyFeedback" )
usethis::use_package("shinyWidgets")
usethis::use_package("janitor")
usethis::use_package("glue")
usethis::use_package("reactable")
usethis::use_package("shinydashboard")
usethis::use_package("shinycssloaders")
usethis::use_pipe()
